const CACHE='bayer-plt-tools-v1-2-0-release';
const CORE=['./','./index.html','./assets/styles.css','./assets/start-mobile.css','./assets/app.js','./assets/stabilisierung.css','./assets/stabilisierung.js','./assets/efup-photo-page-fix.js','./assets/app-version-1.2.0.js','./assets/wissensvorlage-integration.css','./assets/wissensvorlage-integration.js','./assets/bayer-logo-web.webp','./assets/icon-192.png','./assets/icon-512.png','./wissensdatenbank/','./wissensdatenbank/index.html','./wissensdatenbank/vorlagen/Wissensdatenbank_Beitragsvorlage.docx'];
const MODULES='analogsignal|pf-rechner|pt-rechner|messstellen-doku|servicewerte|einheitenrechner|wissensdatenbank';
function base(url){const p=new URL(url).pathname,m=p.match(new RegExp('/('+MODULES+')/'));return m?p.slice(0,m.index+1):(p.endsWith('/')?p:p.slice(0,p.lastIndexOf('/')+1))}
function patchPhotoPages(h){if(!h.includes('/messstellen-doku/')&&!h.includes('Messstellen-Dokumentation'))return h;const patterns=[["if($(key+'None').checked)entries.push({title,note:'Foto nicht benoetigt.'});else","if($(key+'None').checked){}else"],["if ($(key + 'None').checked) entries.push({ title, note: 'Foto nicht benoetigt.' }); else","if ($(key + 'None').checked) {} else"],["if($(key+'None').checked){entries.push({title,note:'Foto nicht benoetigt.'})}else","if($(key+'None').checked){}else"]];for(const [a,b] of patterns)h=h.replace(a,b);return h}
async function enhance(r,q){if(!r||!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return r;let h=patchPhotoPages(await r.text()),b=base(q.url);h=h.replace(/<script[^>]+app-version-[^>]+><\/script>/gi,'').replace(/<script[^>]+wissensvorlage-integration\.js[^>]*><\/script>/gi,'').replace(/<script[^>]+efup-photo-page-fix\.js[^>]*><\/script>/gi,'').replace(/<link[^>]+wissensvorlage-integration\.css[^>]*>/gi,'').replace('</head>',`<link rel="stylesheet" href="${b}assets/wissensvorlage-integration.css?v=1.2.0"><script defer src="${b}assets/efup-photo-page-fix.js?v=1.2.0"></script><script defer src="${b}assets/wissensvorlage-integration.js?v=1.2.0"></script><script defer src="${b}assets/app-version-1.2.0.js?v=1.2.0"></script></head>`);const x=new Headers(r.headers);x.delete('content-length');x.set('content-type','text/html; charset=utf-8');return new Response(h,{status:r.status,statusText:r.statusText,headers:x})}
self.addEventListener('install',e=>{self.skipWaiting();e.waitUntil(caches.open(CACHE).then(c=>c.addAll(CORE)))});
self.addEventListener('activate',e=>e.waitUntil(caches.keys().then(k=>Promise.all(k.filter(x=>x!==CACHE).map(x=>caches.delete(x)))).then(()=>self.clients.claim())));
self.addEventListener('fetch',e=>{const q=e.request;if(q.mode==='navigate'){e.respondWith(fetch(q,{cache:'no-store'}).then(r=>enhance(r,q)).catch(()=>caches.match(q).then(r=>enhance(r,q))));return}e.respondWith(fetch(q).catch(()=>caches.match(q)))})
