const CACHE='sk-plt-tools-v1.5.0-safepoint-candidate';
const CORE=['./','./index.html','./manifest.webmanifest','./assets/styles.css','./assets/app.js','./assets/version-1.5.0.js','./assets/favorites.css','./assets/favorites.js','./assets/logo.png','./assets/icon-192.png','./assets/icon-512.png','./assets/apple-touch-icon.png','./assets/favicon.png'];
const MODULES='analogsignal|pf-rechner|pt-rechner|einheitenrechner|messstellen-doku|servicewerte|wissensdatenbank';
function base(url){const path=new URL(url).pathname;const match=path.match(new RegExp('/('+MODULES+')/'));return match?path.slice(0,match.index+1):(path.endsWith('/')?path:path.slice(0,path.lastIndexOf('/')+1))}
function replaceVersion(text){return text.replace(/Version\s+[0-9]+\.[0-9]+\.[0-9]+/gi,'Version 1.5.0').replace(/const\s+APP_VERSION\s*=\s*['"][0-9]+\.[0-9]+\.[0-9]+['"]/,'const APP_VERSION=\'1.5.0\'')}
async function enhanceHtml(response,request){if(!response||!response.ok)return response;let html=replaceVersion(await response.text());const root=base(request.url);html=html.replace(/<link[^>]+favorites\.css[^>]*>/gi,'').replace(/<script[^>]+(?:favorites|version-1\.5\.0)\.js[^>]*><\/script>/gi,'').replace('</head>',`<link rel="stylesheet" href="${root}assets/favorites.css?v=1.5.0"></head>`).replace('</body>',`<script src="${root}assets/favorites.js?v=1.5.0"></script><script src="${root}assets/version-1.5.0.js?v=1.5.0"></script></body>`);const headers=new Headers(response.headers);headers.delete('content-length');headers.set('content-type','text/html; charset=utf-8');headers.set('cache-control','no-store');return new Response(html,{status:response.status,statusText:response.statusText,headers})}
async function enhanceJs(response){if(!response||!response.ok)return response;const text=replaceVersion(await response.text());const headers=new Headers(response.headers);headers.delete('content-length');headers.set('content-type','application/javascript; charset=utf-8');headers.set('cache-control','no-store');return new Response(text,{status:response.status,statusText:response.statusText,headers})}
self.addEventListener('install',event=>{self.skipWaiting();event.waitUntil(caches.open(CACHE).then(cache=>cache.addAll(CORE)))});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener('fetch',event=>{const request=event.request;if(request.mode==='navigate'){event.respondWith(fetch(request,{cache:'no-store'}).then(response=>enhanceHtml(response,request)).catch(()=>caches.match(request).then(response=>enhanceHtml(response,request))));return}if(new URL(request.url).pathname.endsWith('/assets/app.js')){event.respondWith(fetch(request,{cache:'no-store'}).then(enhanceJs).catch(()=>caches.match(request).then(enhanceJs)));return}event.respondWith(fetch(request,{cache:'no-store'}).then(response=>{const copy=response.clone();caches.open(CACHE).then(cache=>cache.put(request,copy));return response}).catch(()=>caches.match(request)))});
